/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
colors: {
  background: '#ffffff',
  'surface-variant': '#E7E5DF',
  'on-error': '#ffffff',
  'surface-container': '#F4F3EF',
  'error-container': '#ffdad6',
  'surface-container-low': '#ffffff',
  tertiary: '#8C5A47',
  'on-background': '#222222',
  'surface-container-highest': '#E7E5DF',
  surface: '#ffffff',
  'inverse-on-surface': '#F4F3EF',
  'on-surface-variant': '#5f5e5e',
  'on-primary-fixed-variant': '#38523B',
  'on-primary-container': '#ffffff',
  'tertiary-fixed-dim': '#E7E5DF',
  'inverse-primary': '#E7E5DF',
  'secondary-container': '#F4F3EF',
  'surface-container-lowest': '#ffffff',
  'on-tertiary-fixed': '#222222',
  'primary-container': '#38523B',
  'on-secondary-container': '#222222',
  'inverse-surface': '#222222',
  'secondary-fixed': '#E7E5DF',
  'secondary-fixed-dim': '#E7E5DF',
  'outline-variant': '#E7E5DF',
  outline: '#8C5A47',
  secondary: '#000000',
  'surface-bright': '#ffffff',
  'on-primary-fixed': '#222222',
  'surface-dim': '#E7E5DF',
  'surface-container-high': '#E7E5DF',
  'on-secondary-fixed-variant': '#8C5A47',
  'on-primary': '#ffffff',
  'on-tertiary-fixed-variant': '#8C5A47',
  'on-secondary-fixed': '#222222',
  error: '#ba1a1a',
  'primary-fixed-dim': '#E7E5DF',
  'on-tertiary': '#ffffff',
  'tertiary-container': '#8C5A47',
  primary: '#38523B',
  'primary-fixed': '#E7E5DF',
  'surface-tint': '#38523B',
  'on-surface': '#222222',
  'on-tertiary-container': '#ffffff',
  'on-error-container': '#93000a',
  'on-secondary': '#ffffff',
  'tertiary-fixed': '#E7E5DF',

  // Tus últimos 8 agregados sin modificar:
  navcolor: '#38523B',
  fontcolor: '#F4F3EF',
  coloreje: '#8C5A47',
  colorbody: '#F4F3EF',
  fondosegundario: '#5b5544',
  titulos: '#222222',
  colorprimario: '#38523B',
  coloracento: '#8C5A47',
},
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'grid-columns': '12',
        'section-gap-md': '80px',
        'section-gap-lg': '120px',
        'container-max-width': '1280px',
        base: '8px',
        gutter: '24px',
      },
      fontFamily: {
        sans: ['Noto Sans', 'sans-serif'],
        'label-md': ['Noto Sans', 'sans-serif'],
        'display-lg': ['Noto Sans', 'sans-serif'],
        'headline-lg': ['Noto Sans', 'sans-serif'],
        'body-lg': ['Noto Sans', 'sans-serif'],
        'headline-xl-mobile': ['Noto Sans', 'sans-serif'],
        'body-md': ['Noto Sans', 'sans-serif'],
        'headline-xl': ['Noto Sans', 'sans-serif'],
        'headline-md': ['Noto Sans', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-xl-mobile': ['36px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-xl': ['48px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
