/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        background: '#ffffff',
        'surface-variant': '#e2e2e2',
        'on-error': '#ffffff',
        'surface-container': '#eeeeee',
        'error-container': '#ffdad6',
        'surface-container-low': '#f3f3f3',
        tertiary: '#000000',
        'on-background': '#1a1c1c',
        'surface-container-highest': '#e2e2e2',
        surface: '#f9f9f9',
        'inverse-on-surface': '#f1f1f1',
        'on-surface-variant': '#4c4546',
        'on-primary-fixed-variant': '#474747',
        'on-primary-container': '#848484',
        'tertiary-fixed-dim': '#c7c6c6',
        'inverse-primary': '#c6c6c6',
        'secondary-container': '#e4e2e1',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#1b1c1c',
        'primary-container': '#1b1b1b',
        'on-secondary-container': '#656464',
        'inverse-surface': '#2f3131',
        'secondary-fixed': '#e4e2e1',
        'secondary-fixed-dim': '#c8c6c6',
        'outline-variant': '#cfc4c5',
        outline: '#7e7576',
        secondary: '#5f5e5e',
        'surface-bright': '#f9f9f9',
        'on-primary-fixed': '#1b1b1b',
        'surface-dim': '#dadada',
        'surface-container-high': '#e8e8e8',
        'on-secondary-fixed-variant': '#474747',
        'on-primary': '#ffffff',
        'on-tertiary-fixed-variant': '#464747',
        'on-secondary-fixed': '#1b1c1c',
        error: '#ba1a1a',
        'primary-fixed-dim': '#c6c6c6',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#1b1c1c',
        primary: '#000000',
        'primary-fixed': '#e2e2e2',
        'surface-tint': '#5e5e5e',
        'on-surface': '#1a1c1c',
        'on-tertiary-container': '#848484',
        'on-error-container': '#93000a',
        'on-secondary': '#ffffff',
        'tertiary-fixed': '#e4e2e2',
        navcolor: '#38523B',
        fontcolor: '#F4F3EF',
        coloreje: '#8C5A47',
        colorbody: '#F4F3EF',
        fondosegundario: '#5b5544',
        titulos: '#222222',
        colorprimario: '#38523B',
        coloracento: '#8C5A47',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'grid-columns': '12',
        'section-gap-md': '80px',
        'section-gap-lg': '120px',
        'container-max-width': '1280px',
        base: '8px',
        gutter: '24px',
      },
      fontFamily: {
        sans: ['Noto Sans', 'sans-serif'],
        'label-md': ['Noto Sans', 'sans-serif'],
        'display-lg': ['Noto Sans', 'sans-serif'],
        'headline-lg': ['Noto Sans', 'sans-serif'],
        'body-lg': ['Noto Sans', 'sans-serif'],
        'headline-xl-mobile': ['Noto Sans', 'sans-serif'],
        'body-md': ['Noto Sans', 'sans-serif'],
        'headline-xl': ['Noto Sans', 'sans-serif'],
        'headline-md': ['Noto Sans', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-xl-mobile': ['36px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-xl': ['48px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
